### ISSUE TITLE
Wish: Require/Import in NodeJS way.

### ISSUE THREAD

**Issue by boyw165** [greensock/GreenSock-JS#114] opened 2015-09-11 03:03 UTC
Hi guys,

I import it in NodeJS way and use `webpack` (instead of `bower`, cause `webpack` is more powerful) to compile. It will show error like following.

```
error given was: ReferenceError: document is not defined
  at Function.<anonymous> (/.../node_modules/gsap/src/minified/TweenMax.min.js:15:5081)
  at [object Object].check (/.../node_modules/gsap/src/minified/TweenLite.min.js:12:817)
  at new p (/.../node_modules/gsap/src/minified/TweenLite.min.js:12:1104)
  at t._gsDefine (/.../node_modules/gsap/src/minified/TweenLite.min.js:12:1154)
```

I've read the article [thread](http://greensock.com/forums/topic/11484-using-gsap-with-nodejs/?p=46715) talking about this.

The current workaround for me is tell webpack (by adding rules in its configuration file) where to find the `TweenMax`, `TimelineMax`, and so, instead of requiring `gsap` cause it doesn't work for this moment.

e.g. webpack.config.js

```
  resolve: {
    alias: {
      'TweenLite': path.resolve(MODULE_DIR, 'gsap/src/minified/TweenLite.min.js'),
      'TweenMax': path.resolve(MODULE_DIR, 'gsap/src/minified/TweenMax.min.js'),
      'TimelineLite': path.resolve(MODULE_DIR, 'gsap/src/minified/TimelineLite.min.js'),
      'TimelineMax': path.resolve(MODULE_DIR, 'gsap/src/minified/TimelineMax.min.js'),
      'EasePack': path.resolve(MODULE_DIR, 'gsap/src/minified/easing/EasePack.min.js')
    }
  }
```

Actually I think it would be nice to use `gsap` like this:

```
import {TweenMax, TimelineMax, Back, Quad} from 'gsap';
```

**Comment by danehansen** [comment] 2015-11-20 01:44
@boyw165 Hey I am battling a problem similar to your own right now. Its a private repo so I dont have a github link to show, and I didn't set up the build system (at a new job) but I am wondering how to get different gsap modules to all play nicely here. In our wepback.config.babel.js I've got:
```javascript
  resolve: {
    alias: {
      'TweenLite': 'gsap/src/uncompressed/TweenLite.js',
      'TimelineLite': 'gsap/src/uncompressed/TimelineLite.js',
      'CSSPlugin': 'gsap/src/uncompressed/plugins/CSSPlugin.js',
    },
    root: path.join(__dirname, 'static/src'),
    modulesDirectories: ['node_modules', ...subProjects.map(prefixProject)],
    extensions: ['', '.json', '.js', '.jsx']
  },
```
Then my import statements in my component looking like:
```javascript
import TweenLite from 'TweenLite'
import TimelineLite from 'TimelineLite'
import CSSPlugin from 'CSSPlugin'
```
Logging out out TweenLite so far just gives me an empty object, and then it just doesn't work of course. I realize i'm probably not providing enough information to be helpful, because I don't know what else to include, but if you think you would have any insights, I can provide you with whatever information you would need. Thank you.

**Comment by runspired** [comment] 2015-12-31 15:15
It appears the module definition is globals only:

- https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenLite.js#L15-L18
- https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenLite.js#L1888

It should be something more like this:
```
// this prevents errors when TweenLite is loaded in the presence of an AMD
//  style loader but by script tag, not by the loader.
var freeGlobal = (typeof window !== 'undefined' ? window : (typeof self !== 'undefined' ? self : {})); // jshint ignore:line
freeGlobal.TweenLite = TweenLite

if (typeof define === 'function' && define.amd) {
    define(function() {
        return TweenLite;
    });
} else if (typeof module != 'undefined' && module.exports) {
    module.exports = TweenLite;
} else {
    window[exportName] = TweenLite;
}
```

**Comment by salzhrani** [comment] 2016-01-29 08:48
I have started es6-ification of greensock... you can find it [here](https://github.com/salzhrani/GreenSock-JS/commits/es6) feedback/help is appreciated.
since tests are probably located outside this repo, It is difficult to tell if regressions were introduced.

**Comment by vedmant** [comment] 2016-01-31 16:50
+1 I use it with React JS!

**Comment by akbr** [comment] 2016-02-25 22:54
+1 Would be *really* nice to have modern require/import without global variables.

**Comment by arthurmuchir** [comment] 2016-02-28 16:56
+1

**Comment by lostpebble** [comment] 2016-03-15 07:31
With Webpack's new [Tree Shaking](https://medium.com/modus-create-front-end-development/webpack-2-tree-shaking-configuration-9f1de90f3233#.s9jnwe7e4) configuration this would be an amazing addition to the library. Basically having everything at your disposal but importing just what you need from the ES6 module, with webpack doing the work of cutting out the unused fat.

**Comment by Kerumen** [comment] 2016-03-15 17:32
+1

**Comment by timdoes** [comment] 2016-03-20 14:42
+1

**Comment by JoostKiens** [comment] 2016-03-22 19:59
+1

**Comment by praneybehl** [comment] 2016-03-22 22:46
+1

**Comment by dahannes** [comment] 2016-04-01 08:02
+1

**Comment by glebmachine** [comment] 2016-04-04 14:48
+1

**Comment by dwilt** [comment] 2016-04-05 09:57
+1

**Comment by Iuriy-Budnikov** [comment] 2016-04-05 21:32
+1

**Comment by EugeneHlushko** [comment] 2016-04-13 13:29
+1

**Comment by byzyk** [comment] 2016-04-13 13:31
+1

**Comment by ollie101** [comment] 2016-04-25 14:59
+1 - having to go back to Velocity as I can't have the gsap module polluting the global scope

**Comment by jackdoyle** [comment] 2016-04-25 16:06
Thanks for all the votes, guys. We're definitely exploring this and hear you loud and clear. Thanks for your patience. @ollie101, I'm curious - why the fear of the global scope so much that it'd make you revert to an entirely different engine and miss out on all the unique GSAP features & performance? Not criticizing at all - just trying to understand the reasoning.

**Comment by krzysztofpniak** [comment] 2016-04-25 21:17
@jackdoyle Is there any  milestone for modern imports scheduled?

**Comment by jackdoyle** [comment] 2016-04-25 21:31
@krzysztofpniak I can't commit to a schedule yet, no - it's an ambitious undertaking for a library like this (much more complex than for a library like Velocity) but rest assured that we're moving that direction. It's very difficult to predict exactly how long it's going to take. We prefer to under-promise and over-deliver :) I've got all sorts of ideas for new tools and improvements.

**Comment by kmpkt** [comment] 2016-04-28 13:16
+1

**Comment by krzysztofpniak** [comment] 2016-04-28 14:33
Is it really a big deal? It looks like 1h of work or lets say 1 day if you really want to make it carefully: http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/

**Comment by jackdoyle** [comment] 2016-04-29 07:46
@krzysztofpniak oh, yes, that has been implemented for quite some time. Are you not seeing it in there?Or do you have a specific suggestion for improvement in that regard? Plenty of people have been using GSAP in node, RequireJS, Browserify, etc. 

I was talking about a much bigger overhaul that involves shifting a lot of code around and rewriting entire portions. That'll take weeks if not months.

**Comment by dwilt** [comment] 2016-05-04 00:26
@jackdoyle I had a lot of trouble just importing pieces of the GSAP plugin. Have you tried it yourself with something like Webpack and the following?:

```javascript
import {TweenMax, TimelineMax, Back, Quad} from 'gsap';
```

**Comment by Iuriy-Budnikov** [comment] 2016-05-04 07:27
Unfortunately import doesn't work.

**Comment by jackdoyle** [comment] 2016-05-26 05:44
This should be largely resolved in the latest version, 1.18.5 (released today). Let me know if you run into any issues.

**Closed by jackdoyle** 2016-05-26 05:44 UTC

**Comment by glebmachine** [comment] 2016-05-26 05:46
Great news guys! Thank you)

**Comment by kmpkt** [comment] 2016-05-26 09:15
Awesome. Thank you.

**Comment by salzhrani** [comment] 2016-06-01 09:00
Anyone got it working using `import { TweenLite } from 'gsap'` with webpack? not sure if I have bad config

**Comment by jackdoyle** [comment] 2016-06-02 00:32
Yep, I got it to work fine. @salzhrani, are you sure you're using the latest (1.18.5)?

**Comment by salzhrani** [comment] 2016-06-02 09:40
I am using webpack beta ... calls [here](https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenMax.js#L5891) before `ns == 'TweenMax'` skip [this line](https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenMax.js#L5920) because `_exports[moduleName]` is `undefined`. once `ns == 'TweenMax'` happens  `_exports[moduleName]` becomes truthy and the following calls do reach [this line](https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TweenMax.js#L5920) and get registered. In my setup classes like `Power0` and `TweenLite` are missing from `module.exports`

**Comment by jackdoyle** [comment] 2016-06-05 04:51
I see what you mean, yes. Is this any better?: https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/TweenMax-latest-beta.js

**Comment by salzhrani** [comment] 2016-06-12 10:06
@jackdoyle sorry for the late response ... I tried the build and it exhibits the same issue.

**Comment by jackdoyle** [comment] 2016-06-14 20:19
@salzhrani hm, are you sure you weren't using some cached version or something? I just triple-checked, even in someone else's project and it worked exactly as expected. Do you have a reduced test case that shows it broken even with that new version that I linked to above?

**Comment by kmpkt** [comment] 2016-06-17 12:48
Works like a charm. Thank you.

**Comment by Blueblau** [comment] 2016-07-21 16:43
@jackdoyle It works fine with TweenMax and TimelineMax, but importing utils like Draggable, then you get an error about TweenLite module not found.
`ERROR in ./src/vendor/gsap/utils/Draggable.js
Module not found: Error: Cannot resolve module 'TweenLite' in /Users/kennethbrogger/Projects/temp/Crashtestjimmy/src/vendor/gsap/utils
 @ ./src/vendor/gsap/utils/Draggable.js 13:57486-57517`

**Comment by jackdoyle** [comment] 2016-07-21 16:52
Seems to work fine if you tweak your Webpack config, like: 
```javascript
resolve: {
  root: path.resolve(__dirname),
  extensions: ['', '.js'],
  alias: {
    "TweenLite": "src/libs/gsap/TweenLite",
    "CSSPlugin": "src/libs/gsap/plugins/CSSPlugin"
  }
}
```
Then, I just import Draggable like: 
```javascript
import Draggable from "./libs/gsap/utils/Draggable";
```
(obviously tweak the paths to whatever is appropriate for your setup)

**Comment by Blueblau** [comment] 2016-07-21 17:27
I don't get the buid issues any longer, but I can't get it to work in the browser. The `Draggable` variable is undefined, so I get

> Cannot read property 'create' of undefined

**Comment by glebmachine** [comment] 2016-07-21 17:28
Check my `alias` part of webpack config:
```js
alias: {
      TweenMax: 'gsap/src/uncompressed/TweenMax.js',
      TweenLite: 'gsap/src/uncompressed/TweenLite.js',
      TimelineLite: 'gsap/src/uncompressed/TimelineLite.js',
      TimelineMax: 'gsap/src/uncompressed/TimelineMax.js',
      EasePack: 'gsap/src/uncompressed/easing/EasePack.js',
      CSSPlugin: 'gsap/src/uncompressed/plugins/CSSPlugin.js',
    },
```

**Comment by jackdoyle** [comment] 2016-07-21 17:36
@Blueblau tough to troubleshoot blind, but how exactly are you importing Draggable? I just verified that it worked great for me using Webpack. The element was indeed draggable. No errors. [scratching head]

**Comment by Blueblau** [comment] 2016-07-21 17:41
Still no luck. `Draggable` remains `undefined`.

**Webpack config:**
``` Javascript
    alias: {
      'src': path.resolve(__dirname, '../src'),
      'assets': path.resolve(__dirname, '../src/assets'),
      'components': path.resolve(__dirname, '../src/components'),
      TweenMax: path.resolve(__dirname, '../node_modules/gsap/src/uncompressed/TweenMax.js'),
      TweenLite: path.resolve(__dirname, '../node_modules/gsap/src/uncompressed/TweenLite.js'),
      TimelineLite: path.resolve(__dirname, '../node_modules/gsap/src/uncompressed/TimelineLite.js'),
      TimelineMax: path.resolve(__dirname, '../node_modules/gsap/src/uncompressed/TimelineMax.js'),
      EasePack: path.resolve(__dirname, '../node_modules/gsap/src/uncompressed/easing/EasePack.js'),
      CSSPlugin: path.resolve(__dirname, '../node_modules/gsap/src/uncompressed/plugins/CSSPlugin.js')
    }
```

**Hello.vue**
``` Javascript
  import { TweenMax, TimelineMax, Power3 } from "gsap";
  import { Draggable } from "../vendor/gsap/utils/Draggable.js";
```

I also tried with only from node_modules, and only from my local vendor folder - both unsuccessfully.

**Comment by jackdoyle** [comment] 2016-07-21 17:51
Ah, I think the problem is that you're using { Draggable } instead of just Draggable in your import statement. 
```javascript
//BAD:
import { Draggable } from "../vendor/gsap/utils/Draggable.js";
//GOOD: 
import Draggable from "../vendor/gsap/utils/Draggable.js";
```

**Comment by glebmachine** [comment] 2016-07-21 17:53
@Blueblau Yes, you have use Destructuring assignment https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

This is the same like:
```js
var _obj = require('Draggable');
var Draggable = _obj.Draggable;
```

**Comment by Blueblau** [comment] 2016-07-21 17:53
@jackdoyle Oh... Thanks... 👍  Still new to ES6... 😆

**Comment by jackdoyle** [comment] 2016-07-21 17:56
No problem. Me too!

**Comment by Iuriy-Budnikov** [comment] 2016-07-22 07:36
awesome 👍

**Comment by cgarnier** [comment] 2016-10-11 08:08
Why do you close it ?
gsap is still not working in a standard way with imports.

**Comment by jackdoyle** [comment] 2016-10-12 05:50
@cgarnier We're not aware of any issues here. Everyone we've spoken to who originally had issues as described above got it working (sometimes they just needed to define an alias in their config file). There isn't really a universal way that works flawlessly in every single build system, but we've done several things to make it workable in the vast majority (if not all) of them while also staying fully compatible with ES5 and "regular" browsers. 

Furthermore, it's not as simple as just rebuilding everything in ES6 because there are plenty of caveats with that as well. For example, we're hyper-focused on performance but we've read that ES6 transpilers often introduce nasty slowdowns and bloat the ES5 code. We're still looking into that, but unfortunately it's just not as simple and clean as you might expect ("crappy workaround...just fix your lib"). If you have a specific solution that'd address these concerns, we'd certainly love to see it. In the mean time, we'll keep moving forward and looking for a good ES6-and-ES5-solution-that-doesn't-slow-things-down-or-break-stuff :)

**Comment by cgarnier** [comment] 2016-10-12 07:32
Ok, thanks for this explanation

**Comment by jide** [comment] 2016-10-25 17:09
ES6 and transpilers apart, there should be a clean export of all modules using commonjs. In 2016 most of us expect being able to require a npm module straightforward :)

It's unfortunate that this issue pushes people away from the lib imho.

I tried to make a simple commonjs export of all modules, but the export system is so obscure and undocumented that I failed.

Any reason why we can't do this ?
```
module.exports = {
  // List of modules here
}
```

**Comment by cgarnier** [comment] 2016-10-26 07:24
You can do that

**Comment by jide** [comment] 2016-10-26 12:15
:) I tried, but was unable to import other modules and then reexport them. It throws on importing TimelineMax
```
Error: Cannot resolve module 'TweenLite'
```
which comes from
```
		require("./TweenLite.js"); //dependency
		module.exports = getGlobal();
```
And I can't figure out why.

**Comment by cgarnier** [comment] 2016-10-26 15:45
yes it s 'normal'. gsap is not designed as modules so it wont works.

If you are using webpack, you can do that:
https://github.com/greensock/GreenSock-JS/issues/114#issuecomment-234328469
aliases do the trick.

With a cdn your can exports window.TweenMax

**Comment by jide** [comment] 2016-10-26 22:09
Yes I'm aware of that, and of the alias trick. That's the point :)

I've had issues where one project depending on gsap had gsap as a peerDep, this "design" makes this kind of things harder to set up. That's why I'd have liked to try to add proper commonjs export.
But as I said, I did not succeed.

I ended up using globals in my project. But I did not want to solve my own use case, I wanted to see if and why this is not possible -- and I still fail to see why it would not be.

**Comment by bfred-it** [comment] 2017-01-18 09:30
As an update to this:

## GSAP 1.19.1 and up works without aliases

This the correct code:

```js
import TweenMax from 'gsap';

// or separately:
import TweenLite from 'gsap/TweenLite';
import CSSPlugin from 'gsap/CSSPlugin';
import TimelineLite from 'gsap/TimelineLite';
```

Or this:

```js
import {TweenMax, TimelineMax, Back, Quad} from 'gsap';
```

But not every module can be imported in a single import; for example you **have to** use this for Draggable:

```js
import Draggable from 'gsap/Draggable';
```

**Comment by glebmachine** [comment] 2017-01-18 09:44
Does 1.19.1 is treeshakable?

Do you test it with webpack2 or rollup tree shaking?

**Comment by bfred-it** [comment] 2017-01-18 09:51
No, it's not tree-shakable. `import {TweenMax, TimelineMax, Back, Quad} from 'gsap';` still only points to the TweenMax.js file

**Comment by glebmachine** [comment] 2017-01-18 10:53
Bad news(

**Comment by bfred-it** [comment] 2017-01-18 11:23
If file size is important you can easily import just what you need:

```js
import TweenLite from 'gsap/TweenLite';
import CSSPlugin from 'gsap/CSSPlugin';
import TimelineLite from 'gsap/TimelineLite';
```

Just _not TweenMax_

**Comment by glebmachine** [comment] 2017-01-18 11:24
Ok, thanks)

**Comment by born2net** [comment] 2017-01-31 14:11
I am trying to get GSAP working with Webpack (via Angular 2) and can't see to import using all latest libs:

```
import "gsap";
import 'gsap/CSSPlugin';
import Draggable from 'gsap/Draggable';
import TweenLite from 'gsap/TweenLite';
```
Typescript error: ```Error:(114, 17) TS2304:Cannot find name 'TweenLite'.``` and rest of functions
Webpack error: ```

ERROR in ./src/app/app-module.ts
Module build failed: Error: C:/msweb/studioweb/src/app/app-module.ts (50,23): Cannot find module 'gsap/Draggable'.)
C:/msweb/studioweb/src/app/app-module.ts (51,23): Cannot find module 'gsap/TweenLite'.)
    at _checkDiagnostics (C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:145:15)
    at C:\msweb\studioweb\node_modules\@ngtools\webpack\src\loader.js:172:17
 @ ./src/main.ts 5:0-45
 @ multi webpack-dev-server/client?http://localhost:4208/ ./src/main.ts
 ```
any ideas?

regards

Sean

**Comment by jackdoyle** [comment] 2017-01-31 19:27
@born2net please open a new issue for things like this (otherwise everyone else on this thread gets notified and it's probably not directly related to the original post). 

It sounds like maybe you're not using the latest (1.19.1). Tough to diagnose without more info. Feel free to open a new issue and share more info about your setup and how to reproduce the issue.
